### ISSUE TITLE
JSON mapping missing for Page

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#106]
As a leftover from https://github.com/oasp/oasp4j/pull/690 we still are lacking full support for springs pagination and JSON mapping with Jackson. It is a pitty that all this does not come OOTB. At least again a gap to fill by devon4j. I always expected MTS to reveal such things but for some strange reason it did not.

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.data.domain.Page` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1354)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:367)
	... 39 more
```

**Comment by hohwille** [comment]
See related #29

**Comment by hohwille** [comment]
Fix can be copied from here:
* https://github.com/devonfw-forge/keywi/blob/master/core/src/main/java/com/devonfw/keywi/general/common/impl/config/JsonPage.java
* https://github.com/devonfw-forge/keywi/blob/master/core/src/main/java/com/devonfw/keywi/general/common/impl/config/ApplicationObjectMapperFactory.java#L41
```
    module.addAbstractTypeMapping(Page.class, JsonPage.class);
    module.setMixInAnnotation(Page.class, JsonPage.class);
```
See also this:
```
    module.addSerializer(IdRef.class, new IdRefJsonSerializer());
    module.addDeserializer(IdRef.class, new IdRefJsonDeserializer());
```
As devon4j ships with IdRef but is lacking JSON serializer / deserializer what should also be added to devon4j. IMHO it is a mistake that we do not register all the defaults already OOTB in our `ObjectMapperFactory` in a protected method that may still be overridden. However, fixing bugs in the archetype does not help projects that have started before and copied the "bug" from a previous version.

**Comment by hohwille** [comment]
FYI: To reproduce the bug you need a scenario where a Page is deserialized from JSON.
In MTS the deserialization only happens in the Angular client. Therefore nobody noticed the problem so far. Also nobody noticed that there are many transient attributes in the JSON that should actually be omitted as they are entirely redundant.
The way I reproduced this error is using the devon4j service client and invoking a service method returning a Page. You can easily add this in a RestServiceTest.
Also `IdRef` has most probably not been used in MTS or many projects and therefore nobody noticed the lacking JSON support for it.

**Comment by hohwille** [comment]
For IdRef, I created #114. Rest is done with #111.
