### ISSUE TITLE
Spring-Test not working with JUnit5 (in Eclipse?)

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#167]
### Expected behavior

As a developer, I want to write JUnits so that I assure quality.

### Actual behavior

Even after fixing #166 locally, I get this error:
```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/reactive/config/DelegatingWebFluxConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
```

See also here:
https://stackoverflow.com/questions/54897910/class-path-resource-org-springframework-web-reactive-config-delegatingwebfluxco

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create devon4j app from app template `3.2.0`
2. Fix #166 by adding junit-platform-launcher:1.4.2 to core pom
3. run JUnit test in eclipse

### Related/Dependent Issues
See #166 

### Affected version:
`devon4j:3.2.0`

**Comment by hohwille** [comment]
I can fix this issue with this dependency:
```
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webflux</artifactId>
			<!-- <version>5.2.1.RELEASE</version> -->
		</dependency>
```
But next I am getting this one:
```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/data/couchbase/config/AbstractReactiveCouchbaseDataConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
```

It seems that also spring-test did not do a proper QA of their releases. All is more or less completely broken. Odd that we did not notice this problem before the release...

**Comment by hohwille** [comment]
Now, it is getting crazy: I created a new app with `devon4j:3.1.0` based on `JUnit4`.
I created a SpringBootTest with WebEnvironment.NONE. When I run it, I get this error:
```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/session/hazelcast/config/annotation/web/http/HazelcastHttpSessionConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
```

It seems I found a severe bug in `spring-test` that seems to be out for a while. I have no clue why this only happens to me and not to million others?!?

**Comment by hohwille** [comment]
Maybe `spring-test` is not widly tested with Java11 (and Eclipse ClassLoader)?

**Comment by hohwille** [comment]
OMG this one was a very stupid error on my side: Autocompleting `SpringBootApp` caused me to use `SpringBootApplication` from springframework in `@SpringBootTest`. Hence, the test was scanning all beans in the spring-boot package.
