### ISSUE TITLE
compiler target version configured to java11?

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon4j#326]
My intention was that we still build devon4j with support for Java8. If that is not required and we can drop the support for Java8 we can close this issue as wontfix.
However, I got this exception:
```
Caused by: java.lang.UnsupportedClassVersionError: com/devonfw/module/httpclient/common/impl/rest/HttpRestClientAsyncAutoConfiguration has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_232]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[na:1.8.0_232]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_232]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_232]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_232]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_232]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_232]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_232]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_232]
```

https://www.baeldung.com/java-lang-unsupportedclassversion#1-java-version-numbers
So `class file version 55.0` is Java11.

What confuses me is that we are setting `java.version` to `1.8` in our parent POM:
https://github.com/devonfw/maven-parent/blob/3ab228d1016e35f069c89016bf56193dc29a4a3d/pom.xml#L16
and devon4j does not override this in general.

**Comment by hohwille** [comment]
OK, I figured it out:
https://github.com/devonfw/devon4j/blob/3268e8e563ec1da885ad07467e41aa8cbfd904c5/modules/http-client/pom.xml#L17

This is absolutely correct and on purpose as the Java HTTP Client is not available in JDK 1.8.
So other modules are still Java 1.8 compatible but the client-http stuff not.
